-- MySQL Script generated by MySQL Workbench
-- Mon Apr 13 17:17:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Molchanuk
-- -----------------------------------------------------
-- 
-- 

-- -----------------------------------------------------
-- Schema Molchanuk
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Molchanuk` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Molchanuk` ;

-- -----------------------------------------------------
-- Table `Molchanuk`.`Shipowners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Shipowners` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Shipowners` (
  `idShipowners` INT NOT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idShipowners`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Country` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Country` (
  `idCountry` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Ship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Ship` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Ship` (
  `Type of vessel` VARCHAR(45) NOT NULL,
  `Ship name` VARCHAR(45) NULL,
  `Shipowners_idShipowners` INT NOT NULL,
  `Country_idCountry` INT NOT NULL,
  PRIMARY KEY (`Type of vessel`, `Shipowners_idShipowners`, `Country_idCountry`),
  INDEX `fk_Ship_Shipowners1_idx` (`Shipowners_idShipowners` ASC) VISIBLE,
  INDEX `fk_Ship_Country1_idx` (`Country_idCountry` ASC) VISIBLE,
  CONSTRAINT `fk_Ship_Shipowners1`
    FOREIGN KEY (`Shipowners_idShipowners`)
    REFERENCES `Molchanuk`.`Shipowners` (`idShipowners`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ship_Country1`
    FOREIGN KEY (`Country_idCountry`)
    REFERENCES `Molchanuk`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Contract for ship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Contract for ship` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Contract for ship` (
  `idContract for ship` INT NOT NULL,
  `Ship_Type of vessel` VARCHAR(45) NOT NULL,
  `Ship_Shipowners_idShipowners` INT NOT NULL,
  `Ship_Country_idCountry` INT NOT NULL,
  PRIMARY KEY (`idContract for ship`),
  INDEX `fk_Contract for ship_Ship1_idx` (`Ship_Type of vessel` ASC, `Ship_Shipowners_idShipowners` ASC, `Ship_Country_idCountry` ASC) VISIBLE,
  CONSTRAINT `fk_Contract for ship_Ship1`
    FOREIGN KEY (`Ship_Type of vessel` , `Ship_Shipowners_idShipowners` , `Ship_Country_idCountry`)
    REFERENCES `Molchanuk`.`Ship` (`Type of vessel` , `Shipowners_idShipowners` , `Country_idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Application for job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Application for job` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Application for job` (
  `idApplication for job` INT NOT NULL,
  `Application number` INT NULL,
  `Application date` DATE NULL,
  `Ship_Type of vessel` VARCHAR(45) NOT NULL,
  `Ship_Shipowners_idShipowners` INT NOT NULL,
  `Ship_Country_idCountry` INT NOT NULL,
  PRIMARY KEY (`idApplication for job`),
  INDEX `fk_Application for job_Ship1_idx` (`Ship_Type of vessel` ASC, `Ship_Shipowners_idShipowners` ASC, `Ship_Country_idCountry` ASC) VISIBLE,
  CONSTRAINT `fk_Application for job_Ship1`
    FOREIGN KEY (`Ship_Type of vessel` , `Ship_Shipowners_idShipowners` , `Ship_Country_idCountry`)
    REFERENCES `Molchanuk`.`Ship` (`Type of vessel` , `Shipowners_idShipowners` , `Country_idCountry`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Jobs` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Jobs` (
  `idJobs` INT NOT NULL,
  `Salary` INT NULL,
  `Estimated date of taking up position` DATE NULL,
  `Application for job_idApplication for job` INT NOT NULL,
  PRIMARY KEY (`idJobs`, `Application for job_idApplication for job`),
  INDEX `fk_Jobs_Application for job1_idx` (`Application for job_idApplication for job` ASC) VISIBLE,
  CONSTRAINT `fk_Jobs_Application for job1`
    FOREIGN KEY (`Application for job_idApplication for job`)
    REFERENCES `Molchanuk`.`Application for job` (`idApplication for job`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Rank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Rank` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Rank` (
  `idRank` INT NOT NULL,
  `Availability of the license office` TINYINT(1) NULL,
  `Confirmation of the license` TINYINT(1) NULL,
  `Confirmation code` INT NULL,
  `Code diploma` INT NULL,
  `Type of diploma` VARCHAR(45) NULL,
  `Jobs_idJobs` INT NOT NULL,
  PRIMARY KEY (`idRank`, `Jobs_idJobs`),
  INDEX `fk_Rank_Jobs1_idx` (`Jobs_idJobs` ASC) VISIBLE,
  CONSTRAINT `fk_Rank_Jobs1`
    FOREIGN KEY (`Jobs_idJobs`)
    REFERENCES `Molchanuk`.`Jobs` (`idJobs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Command`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Command` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Command` (
  `idCommand` INT NOT NULL,
  `Salary` INT NULL,
  `Contract for ship_idContract for ship` INT NOT NULL,
  `Rank_idRank` INT NOT NULL,
  PRIMARY KEY (`idCommand`, `Contract for ship_idContract for ship`),
  INDEX `fk_Command_Contract for ship1_idx` (`Contract for ship_idContract for ship` ASC) VISIBLE,
  INDEX `fk_Command_Rank1_idx` (`Rank_idRank` ASC) VISIBLE,
  CONSTRAINT `fk_Command_Contract for ship1`
    FOREIGN KEY (`Contract for ship_idContract for ship`)
    REFERENCES `Molchanuk`.`Contract for ship` (`idContract for ship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Command_Rank1`
    FOREIGN KEY (`Rank_idRank`)
    REFERENCES `Molchanuk`.`Rank` (`idRank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Files` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Files` (
  `Photo` INT NOT NULL,
  `File` BLOB NULL,
  PRIMARY KEY (`Photo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Profile sailor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Profile sailor` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Profile sailor` (
  `idProfile sailor` INT NOT NULL,
  `Surname` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Patronymic` VARCHAR(45) NULL,
  `Date of birth` DATE NULL,
  `Place of birth` VARCHAR(70) NULL,
  `Home address` VARCHAR(70) NULL,
  `Phone home` VARCHAR(17) NULL,
  `Mobile phone` VARCHAR(17) NULL,
  `Citizenship` VARCHAR(45) NULL,
  `Marital Status` VARCHAR(15) NULL,
  `Height` INT NULL,
  `Weight` INT NULL,
  `Date of medical examination` DATE NULL,
  `Drugs & Alcohol test date` DATE NULL,
  `National passport №` INT NULL,
  `National passport issued` DATE NULL,
  `International passport №` INT NULL,
  `International passport issued` DATE NULL,
  `International passport valid` DATE NULL,
  `Seaman passport №` INT NULL,
  `Seaman passport issued` DATE NULL,
  `Seaman passport valid` DATE NULL,
  `Ready to fight` DATE NULL,
  `In fight` TINYINT NULL,
  `Rank` VARCHAR(45) NULL,
  `License` VARCHAR(45) NULL,
  `Rank with` DATE NULL,
  `Rank on` DATE NULL,
  `Files_Photo` INT NOT NULL,
  PRIMARY KEY (`idProfile sailor`),
  INDEX `fk_Profile sailor_Files1_idx` (`Files_Photo` ASC) VISIBLE,
  CONSTRAINT `fk_Profile sailor_Files1`
    FOREIGN KEY (`Files_Photo`)
    REFERENCES `Molchanuk`.`Files` (`Photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Career`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Career` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Career` (
  `idCareer` INT NOT NULL,
  `Vessel's name` VARCHAR(45) NULL,
  `Shipowner` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `Type of vessel` VARCHAR(45) NULL,
  `Rank` VARCHAR(45) NULL,
  `From` DATE NULL,
  `To` DATE NULL,
  `Profile sailor_idProfile sailor` INT NOT NULL,
  PRIMARY KEY (`idCareer`, `Profile sailor_idProfile sailor`),
  INDEX `fk_Career_Profile sailor1_idx` (`Profile sailor_idProfile sailor` ASC) VISIBLE,
  CONSTRAINT `fk_Career_Profile sailor1`
    FOREIGN KEY (`Profile sailor_idProfile sailor`)
    REFERENCES `Molchanuk`.`Profile sailor` (`idProfile sailor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Knowledge of language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Knowledge of language` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Knowledge of language` (
  `idKnowledge of language` INT NOT NULL,
  `Language` VARCHAR(45) NULL,
  `Proficiency` VARCHAR(45) NULL,
  `Mark` INT NULL,
  `Profile sailor_idProfile sailor` INT NOT NULL,
  PRIMARY KEY (`idKnowledge of language`, `Profile sailor_idProfile sailor`),
  INDEX `fk_Knowledge of language_Profile sailor1_idx` (`Profile sailor_idProfile sailor` ASC) VISIBLE,
  CONSTRAINT `fk_Knowledge of language_Profile sailor1`
    FOREIGN KEY (`Profile sailor_idProfile sailor`)
    REFERENCES `Molchanuk`.`Profile sailor` (`idProfile sailor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Mask phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Mask phone` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Mask phone` (
  `idMask phone` INT NOT NULL,
  `Country` VARCHAR(45) NULL,
  `Mask house` VARCHAR(45) NULL,
  `Mask mobile` VARCHAR(45) NULL,
  `Profile sailor_idProfile sailor` INT NOT NULL,
  PRIMARY KEY (`idMask phone`),
  INDEX `fk_Mask phone_Profile sailor1_idx` (`Profile sailor_idProfile sailor` ASC) VISIBLE,
  CONSTRAINT `fk_Mask phone_Profile sailor1`
    FOREIGN KEY (`Profile sailor_idProfile sailor`)
    REFERENCES `Molchanuk`.`Profile sailor` (`idProfile sailor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`The country issued visa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`The country issued visa` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`The country issued visa` (
  `idThe country issued visa` INT NOT NULL,
  `Country` VARCHAR(45) NULL,
  PRIMARY KEY (`idThe country issued visa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Visas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Visas` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Visas` (
  `idVisas` INT NOT NULL,
  `Date of issue` DATE NULL,
  `Date of` DATE NULL,
  `The type of visa` VARCHAR(45) NULL,
  `Profile sailor_idProfile sailor` INT NOT NULL,
  `The country issued visa_idThe country issued visa` INT NOT NULL,
  PRIMARY KEY (`idVisas`, `Profile sailor_idProfile sailor`, `The country issued visa_idThe country issued visa`),
  INDEX `fk_Visas_Profile sailor1_idx` (`Profile sailor_idProfile sailor` ASC) VISIBLE,
  INDEX `fk_Visas_The country issued visa1_idx` (`The country issued visa_idThe country issued visa` ASC) VISIBLE,
  CONSTRAINT `fk_Visas_Profile sailor1`
    FOREIGN KEY (`Profile sailor_idProfile sailor`)
    REFERENCES `Molchanuk`.`Profile sailor` (`idProfile sailor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visas_The country issued visa1`
    FOREIGN KEY (`The country issued visa_idThe country issued visa`)
    REFERENCES `Molchanuk`.`The country issued visa` (`idThe country issued visa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`License`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`License` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`License` (
  `Date of licensing` DATE NOT NULL,
  PRIMARY KEY (`Date of licensing`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Working papers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Working papers` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Working papers` (
  `idWorking papers` INT NOT NULL,
  `Certificate` VARCHAR(45) NULL,
  `Number` INT NULL,
  `Issued with` DATE NULL,
  `Valid on` DATE NULL,
  `Rank` VARCHAR(45) NULL,
  `License` VARCHAR(45) NULL,
  `License number` INT NULL,
  `License issued` DATE NULL,
  `Valid to` DATE NULL,
  `Confirmation` VARCHAR(45) NULL,
  `Confirmation numder` INT NULL,
  `Confirmation is issued` VARCHAR(45) NULL,
  `Confirmation is valid until` DATE NULL,
  `Education` VARCHAR(60) NULL,
  `With` DATE NULL,
  `To` DATE NULL,
  `Type of diplom` VARCHAR(45) NULL,
  `Code certificate` INT NULL,
  `Certificate number` INT NULL,
  `Date of issue` DATE NULL,
  `Expiration date` DATE NULL,
  `Profile sailor_idProfile sailor` INT NOT NULL,
  `License_Date of licensing` DATE NOT NULL,
  PRIMARY KEY (`idWorking papers`, `Profile sailor_idProfile sailor`),
  INDEX `fk_Working papers_Profile sailor1_idx` (`Profile sailor_idProfile sailor` ASC) VISIBLE,
  INDEX `fk_Working papers_License1_idx` (`License_Date of licensing` ASC) VISIBLE,
  CONSTRAINT `fk_Working papers_Profile sailor1`
    FOREIGN KEY (`Profile sailor_idProfile sailor`)
    REFERENCES `Molchanuk`.`Profile sailor` (`idProfile sailor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Working papers_License1`
    FOREIGN KEY (`License_Date of licensing`)
    REFERENCES `Molchanuk`.`License` (`Date of licensing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Children`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Children` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Children` (
  `idChildren` INT NOT NULL,
  `Next to kin` VARCHAR(60) NULL,
  `Address of nearest relative` VARCHAR(60) NULL,
  `The degree of relationship` VARCHAR(45) NULL,
  `Profile sailor_idProfile sailor` INT NOT NULL,
  PRIMARY KEY (`idChildren`),
  INDEX `fk_Children_Profile sailor1_idx` (`Profile sailor_idProfile sailor` ASC) VISIBLE,
  CONSTRAINT `fk_Children_Profile sailor1`
    FOREIGN KEY (`Profile sailor_idProfile sailor`)
    REFERENCES `Molchanuk`.`Profile sailor` (`idProfile sailor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Logistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Logistics` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Logistics` (
  `idLogistics` INT NOT NULL,
  `Rank` VARCHAR(45) NULL,
  `Profile sailor_idProfile sailor` INT NOT NULL,
  `Ship_Type of vessel` VARCHAR(45) NOT NULL,
  `Ship_Shipowners_idShipowners` INT NOT NULL,
  `Ship_Country_idCountry` INT NOT NULL,
  PRIMARY KEY (`idLogistics`, `Ship_Type of vessel`, `Ship_Shipowners_idShipowners`, `Ship_Country_idCountry`),
  INDEX `fk_Logistics_Profile sailor1_idx` (`Profile sailor_idProfile sailor` ASC) VISIBLE,
  INDEX `fk_Logistics_Ship1_idx` (`Ship_Type of vessel` ASC, `Ship_Shipowners_idShipowners` ASC, `Ship_Country_idCountry` ASC) VISIBLE,
  CONSTRAINT `fk_Logistics_Profile sailor1`
    FOREIGN KEY (`Profile sailor_idProfile sailor`)
    REFERENCES `Molchanuk`.`Profile sailor` (`idProfile sailor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Logistics_Ship1`
    FOREIGN KEY (`Ship_Type of vessel` , `Ship_Shipowners_idShipowners` , `Ship_Country_idCountry`)
    REFERENCES `Molchanuk`.`Ship` (`Type of vessel` , `Shipowners_idShipowners` , `Country_idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Comment` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Comment` (
  `idComment` INT NOT NULL,
  `Location` VARCHAR(45) NULL,
  `Logistics_idLogistics` INT NOT NULL,
  PRIMARY KEY (`idComment`, `Logistics_idLogistics`),
  INDEX `fk_Comment_Logistics1_idx` (`Logistics_idLogistics` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_Logistics1`
    FOREIGN KEY (`Logistics_idLogistics`)
    REFERENCES `Molchanuk`.`Logistics` (`idLogistics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Arrival`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Arrival` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Arrival` (
  `idArrival` INT NOT NULL,
  `Departure date` DATE NOT NULL,
  `Arrival date` DATE NOT NULL,
  `Logistics_idLogistics` INT NOT NULL,
  PRIMARY KEY (`idArrival`, `Departure date`, `Arrival date`, `Logistics_idLogistics`),
  INDEX `fk_Arrival_Logistics1_idx` (`Logistics_idLogistics` ASC) VISIBLE,
  CONSTRAINT `fk_Arrival_Logistics1`
    FOREIGN KEY (`Logistics_idLogistics`)
    REFERENCES `Molchanuk`.`Logistics` (`idLogistics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Departure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Departure` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Departure` (
  `idDeparture` INT NOT NULL,
  `City of` VARCHAR(45) NULL,
  `In the city` VARCHAR(45) NULL,
  `Logistics_idLogistics` INT NOT NULL,
  PRIMARY KEY (`idDeparture`, `Logistics_idLogistics`),
  INDEX `fk_Departure_Logistics1_idx` (`Logistics_idLogistics` ASC) VISIBLE,
  CONSTRAINT `fk_Departure_Logistics1`
    FOREIGN KEY (`Logistics_idLogistics`)
    REFERENCES `Molchanuk`.`Logistics` (`idLogistics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molchanuk`.`Studies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Molchanuk`.`Studies` ;

CREATE TABLE IF NOT EXISTS `Molchanuk`.`Studies` (
  `idStudies` INT NOT NULL,
  `Institutions` VARCHAR(45) NULL,
  `Number diploma` INT NULL,
  `Expiration date` DATE NULL,
  `Profile sailor_idProfile sailor` INT NOT NULL,
  PRIMARY KEY (`idStudies`, `Profile sailor_idProfile sailor`),
  INDEX `fk_Studies_Profile sailor1_idx` (`Profile sailor_idProfile sailor` ASC) VISIBLE,
  CONSTRAINT `fk_Studies_Profile sailor1`
    FOREIGN KEY (`Profile sailor_idProfile sailor`)
    REFERENCES `Molchanuk`.`Profile sailor` (`idProfile sailor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
